# Resolve react_native_pods.rb using node to support hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]}
  )', __dir__]).strip

platform :ios, min_ios_version_supported  # React Native 0.79+ requires at least iOS 13

prepare_react_native_project!
install! 'cocoapods', :deterministic_uuids => false

# Framework linking
linkage = ENV['USE_FRAMEWORKS']
if linkage
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'Gosourcery' do
  config = use_native_modules!

  # Force static framework use (best for compatibility)
  use_frameworks! :linkage => :static

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => false,
    # :hermes_enabled => true,
    # :fabric_enabled => false,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Only include Amplify pods if  you're using native modules
  # For example, uncomment if you're using analytics/storage
  # pod 'Amplify'
  # pod 'AWSCognitoAuthPlugin'
  # pod 'AWSAPIPlugin'
  # pod 'AWSS3StoragePlugin'

  
  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    # Apple Silicon fix for M1–M4: ensure arm64 arch is supported in simulator
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'i386'
        
      end
    end
  end
end

# # Resolve react_native_pods.rb with node to allow for hoisting
# require Pod::Executable.execute_command('node', ['-p',
#   'require.resolve(
#     "react-native/scripts/react_native_pods.rb",
#     {paths: [process.argv[1]]},
#   )', __dir__]).strip

# platform :ios, min_ios_version_supported
# prepare_react_native_project!
# install! 'cocoapods', :deterministic_uuids => false

# linkage = ENV['USE_FRAMEWORKS']
# if linkage != nil
#   Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
#   use_frameworks! :linkage => linkage.to_sym
# end

# target 'Gosourcery' do
#   config = use_native_modules!

#   use_frameworks! :linkage => :static
#   # pod 'React-RCTText', :modular_headers => true

#   # Any others like AWS or camera if needed:
#   # pod 'RCT-Folly', :modular_headers => true

#   use_react_native!(
#     :path => config[:reactNativePath],
#     :hermes_enabled => true,
#     :fabric_enabled => true,
#     # An absolute path to your application root.
#     :app_path => "#{Pod::Config.instance.installation_root}/.."
#   )

#   post_install do |installer|
#     # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
#     react_native_post_install(
#       installer,
#       config[:reactNativePath],
#       :mac_catalyst_enabled => false,
#       # :ccache_enabled => true
#     )
#   end
# end
