export const theme1 = {
    GRADIENT_COLOR: [
        '#0311D0',
        '#4903C6'
    ],
    BLUE_COLOR: '#2479ff',
    YELLOW_COLOR: '#F06F00',
    GREEN_COLOR: '#00a774',
    RED_COLOR: '#da304c',
    BLACK_COLOR: '#0C0C0C',
    WHITE_COLOR: '#FEFEFE',
    LIGHT_GREY_COLOR: '#F7F7F9',
    DARK_GREY_COLOR: '#ACACAC',


    FIRST_TEXT_COLOR: "#FF464B",
    SECOND_TEXT_COLOR: '#2196F3',
    THIRD_TEXT_COLOR: "#1E1E1E",
    FORTH_TEXT_COLOR: "#ACACAC",
    FIFTH_TEXT_COLOR: "#1D242E",
    SIXTH_TEXT_COLOR: "#101010",
    SEVENTH_TEXT_COLOR:"#A8A8A8",
    EIGHT_TEXT_COLOR:"#4F4F4F",
    NINTH_TEXT_COLOR :"#D3D3D3",
    TENTH_TEXT_COLOR:"#9B9A9A",
    ELEVEN_TEXT_COLOR: "#EBF4FF",
    TWELVE_TEXT_COLOR:"#2E2E41",
    THIRTEEN_TEXT_COLOR:"#6C6C6C",
    FOURTEEN_TEXT_COLOR:"#259708",
    FIFTEEN_TEXT_COLOR:"#454545",
    SIXTEEN_TEXT_COLOR:"#B80606",
    SEVENTEEN_TEXT_COLOR:"#564EA1",
    EIGHTEEN_TEXT_COLOR:"#1E1F3A",
    NINTEEN_TEXT_COLOR:"#283640",
    TWENTY_TEXT_COLOR:"#086766",
    TWENTY_ONE_TEXT_COLOR:"#262929",
    TWENTY_TWO_TEXT_COLOR:"#595959",
    TWENTY_THREE_TEXT_COLOR:"#4C4F50",
    TWENTY_FOUR_TEXT_COLOR:"#6DA8BF",
    TWENTY_FIVE_TEXT_COLOR:"#E7E9EA",
    TWENTY_SIX_TEXT_COLOR:"#74B3FF",
    TWENTY_SEVEN_TEXT_COLOR:"#797979",
    TWENTY_EIGHT_TEXT_COLOR:"#353535",
    TWENTY_NINE_TEXT_COLOR:"#C9C9C9",
    THIRTY_TEXT_COLOR:"#FFE4F2",
    THIRTY_ONE_TEXT_COLOR:"#2196F3",
    THIRTY_TWO_TEXT_COLOR:"#4CAF50",
    THIRTY_THREE_TEXT_COLOR:"#FF9800",
    THIRTY_FOUR_TEXT_COLOR:"#9C27B0",
    STAR_EVENT_COLOR:"#CC6BB5",
};

export function getTheme(theme?: number | null) {
    switch (theme) {
        case 1:
            return theme1;
        default:
            return theme1;
    }
}